# =============================================================================
# DEV CONFIG - Local development entry point (320x320 S3 SPI panel)
# =============================================================================
# Flash with: esphome run dev.yaml
# =============================================================================

substitutions:
  cover_art_placeholder_file: "../../common/assets/cover_art_placeholder.svg"
  name: "espcontrol-s3-panel-320"
  friendly_name: "EspControl S3 Panel 320"
  espcontrol_component_url: "../.."
  mdi_font_file: "../../common/assets/fonts/materialdesignicons-webfont-7.4.47.ttf"
  espcontrol_component_ref: "HEAD"

esp32:
  partitions: "../../common/device/partitions_8mb_card_images.csv"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  espcontrol: !include packages.yaml

web_server:
  js_url: ""
  js_include: "../../docs/public/webserver/embedded/www.js"
